// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxbrcramrthbcrjisjpa.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54YnJjcmFtcnRoYmNyamlzanBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NDkzMzcsImV4cCI6MjA4NzQyNTMzN30.riQ3Vb7bVKBvW9kiJgcoQ1-LQgwgSO3AoBqaNYkW_TI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});